In [ ]:
# Numpy-numerical python ndarray,random number generation,-Function----np.array(),np.zeros(),np.arange()
# pandas-panel data,1D-Series,2D-dataframe-csv.tsv,xlsx,(Dataframe-data,index,column),import--pd.read_csv(),pd.to_csv(),pd.fillna(),pd.dropna()
# string
# visualition

In [1]:
pip install numpy

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [7]:
import pandas as pd
import numpy as np

In [5]:
x=[1,2,3,4,5,6,7,8,9]
type(x)

list

In [10]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr
type(arr)

numpy.ndarray

In [12]:
arr_sq=arr**2
arr_sq

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [15]:
arr1=np.arange(0,20)
arr1
type(arr1)

numpy.ndarray

In [17]:
arr1=np.arange(0,20).reshape(5,4)
arr1
#type(arr1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [22]:
data=[10,20,30,40]
series_1=pd.Series(data)
series_1
#type(series_1)

0    10
1    20
2    30
3    40
dtype: int64

In [23]:
series_1=pd.Series(data,index=["A","B","C","D"])
series_1

A    10
B    20
C    30
D    40
dtype: int64

In [26]:
# dict-key:value{}
data={
    'gene':['gene1','gene2','gene3','gene4','gene5','gene6'],
    'Sample1':[1.2,3.4,4.3,5.3,4.6,3.2],
    'Sample2':[1.2,3.4,4.3,5.3,4.6,3.2],
    'Sample3':[1.2,3.4,4.3,5.3,4.6,3.2],
    'Exp_Val':[1.2,3.4,4.3,5.3,4.6,3.2],
}
data
type(data)

dict

In [28]:
df=pd.DataFrame(data)
df

    gene  Sample1  Sample2  Sample3  Exp_Val
0  gene1      1.2      1.2      1.2      1.2
1  gene2      3.4      3.4      3.4      3.4
2  gene3      4.3      4.3      4.3      4.3
3  gene4      5.3      5.3      5.3      5.3
4  gene5      4.6      4.6      4.6      4.6
5  gene6      3.2      3.2      3.2      3.2

In [30]:
df.head()
df.tail()

    gene  Sample1  Sample2  Sample3  Exp_Val
1  gene2      3.4      3.4      3.4      3.4
2  gene3      4.3      4.3      4.3      4.3
3  gene4      5.3      5.3      5.3      5.3
4  gene5      4.6      4.6      4.6      4.6
5  gene6      3.2      3.2      3.2      3.2

In [31]:
df.describe()

        Sample1   Sample2   Sample3   Exp_Val
count  6.000000  6.000000  6.000000  6.000000
mean   3.666667  3.666667  3.666667  3.666667
std    1.436199  1.436199  1.436199  1.436199
min    1.200000  1.200000  1.200000  1.200000
25%    3.250000  3.250000  3.250000  3.250000
50%    3.850000  3.850000  3.850000  3.850000
75%    4.525000  4.525000  4.525000  4.525000
max    5.300000  5.300000  5.300000  5.300000

In [32]:
arr1=np.arange(0,20).reshape(5,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [37]:
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=["Gene1","Gene2","Gene3","Gene4","Gene5"],columns=["Sample1","Sample2","Sample3","Sample4"])
df

       Sample1  Sample2  Sample3  Sample4
Gene1        0        1        2        3
Gene2        4        5        6        7
Gene3        8        9       10       11
Gene4       12       13       14       15
Gene5       16       17       18       19

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Gene1 to Gene5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Sample1  5 non-null      int64
 1   Sample2  5 non-null      int64
 2   Sample3  5 non-null      int64
 3   Sample4  5 non-null      int64
dtypes: int64(4)
memory usage: 372.0+ bytes

In [41]:
df1=df["Sample1"]
df1
type(df1)

pandas.core.series.Series

In [45]:
df1=df[["Sample1","Sample2"]]
df1
type(df1)

pandas.core.frame.DataFrame

In [47]:
df2=df.loc[["Gene1","Gene4"]]
df2

       Sample1  Sample2  Sample3  Sample4
Gene1        0        1        2        3
Gene4       12       13       14       15

In [54]:
np.random.seed(10)
gene_exp=np.random.rand(5,4)*100
gene_exp

array([[77.13206433,  2.07519494, 63.36482349, 74.88038825],
       [49.85070123, 22.47966455, 19.80628648, 76.05307122],
       [16.91108366,  8.83398142, 68.53598184, 95.33933462],
       [ 0.39482663, 51.21922634, 81.26209617, 61.25260668],
       [72.17553174, 29.18760682, 91.77741225, 71.45757834]])

In [55]:
gene_exp

array([[77.13206433,  2.07519494, 63.36482349, 74.88038825],
       [49.85070123, 22.47966455, 19.80628648, 76.05307122],
       [16.91108366,  8.83398142, 68.53598184, 95.33933462],
       [ 0.39482663, 51.21922634, 81.26209617, 61.25260668],
       [72.17553174, 29.18760682, 91.77741225, 71.45757834]])

In [56]:
gene_exp

array([[77.13206433,  2.07519494, 63.36482349, 74.88038825],
       [49.85070123, 22.47966455, 19.80628648, 76.05307122],
       [16.91108366,  8.83398142, 68.53598184, 95.33933462],
       [ 0.39482663, 51.21922634, 81.26209617, 61.25260668],
       [72.17553174, 29.18760682, 91.77741225, 71.45757834]])

In [57]:
np.random.seed(5)
gene_exp_data=np.random.rand(5,4)*100
gene_exp_data

array([[22.19931711, 87.07323062, 20.67191553, 91.86109079],
       [48.84111888, 61.17438629, 76.59078565, 51.84179879],
       [29.68005016, 18.77212287,  8.07412688, 73.84402962],
       [44.13092229, 15.83098677, 87.99370312, 27.4086462 ],
       [41.42350191, 29.60799327, 62.87879089, 57.98378102]])

In [58]:
gene_exp_data

array([[22.19931711, 87.07323062, 20.67191553, 91.86109079],
       [48.84111888, 61.17438629, 76.59078565, 51.84179879],
       [29.68005016, 18.77212287,  8.07412688, 73.84402962],
       [44.13092229, 15.83098677, 87.99370312, 27.4086462 ],
       [41.42350191, 29.60799327, 62.87879089, 57.98378102]])

In [60]:
gene_exp

array([[77.13206433,  2.07519494, 63.36482349, 74.88038825],
       [49.85070123, 22.47966455, 19.80628648, 76.05307122],
       [16.91108366,  8.83398142, 68.53598184, 95.33933462],
       [ 0.39482663, 51.21922634, 81.26209617, 61.25260668],
       [72.17553174, 29.18760682, 91.77741225, 71.45757834]])

In [63]:
gene_data="""Gene,Condition_A,Condition_B,Condition_C,Organism
BRCA1,12.3,14.5,16.2,Homo sapiens
TP53,NaN,10.1,15.5,Homo sapiens
EGFR,22.1,23.3,NaN,Homo sapiens
MYC,18.2,19.5,20.8,Homo sapiens
"""


gene_data

type(gene_data)

str

In [64]:
pip install biopython

Collecting biopython
  Downloading biopython-1.85-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from biopython) (2.0.2)
Downloading biopython-1.85-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 33.1 MB/s eta 0:00:00
Installing collected packages: biopython
Successfully installed biopython-1.85

In [65]:
from Bio import SeqIO
from io import StringIO

In [72]:
df=StringIO(gene_data)
df
df=pd.read_csv(StringIO(gene_data))
df

    Gene  Condition_A  Condition_B  Condition_C      Organism
0  BRCA1         12.3         14.5         16.2  Homo sapiens
1   TP53          NaN         10.1         15.5  Homo sapiens
2   EGFR         22.1         23.3          NaN  Homo sapiens
3    MYC         18.2         19.5         20.8  Homo sapiens

In [74]:
missing_val=df.isnull().sum()
missing_val

Gene           0
Condition_A    1
Condition_B    0
Condition_C    1
Organism       0
dtype: int64

In [76]:
df_filled=df.fillna(df.mean(numeric_only=True))
df_filled

    Gene  Condition_A  Condition_B  Condition_C      Organism
0  BRCA1    12.300000         14.5         16.2  Homo sapiens
1   TP53    17.533333         10.1         15.5  Homo sapiens
2   EGFR    22.100000         23.3         17.5  Homo sapiens
3    MYC    18.200000         19.5         20.8  Homo sapiens